<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System.IO" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\OrdoSort.Wpf\OrdoSort.Wpf.csproj" />
  </ItemGroup>
</Project>
